######### Basic Settings #########
basic:
    device: '6'
    seed: [42, 100, 1993] # 1993, 42, 100

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: false

    # Method Choises: 
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, recall
    eval_metric: acc
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    freeze_fe: false
    save_models: true # if true, programm will save model's weights during incremental train

    note: pretrained

######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100:
        resnet18:
            img_size: 224

            epochs: 200 # 200
            batch_size: 32
            num_workers: 4
            
            opt_type: adam
            lrate: 0.001
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
