######### Basic Settings #########
basic:
    device: '0'
    seed: [42, 50, 100, 1993] # 1, 42, 50, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: false # true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: podnet
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: mcr

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: cosine_resnet18
    pretrained: true
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 16
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean

    apply_nme: true

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 2
    increment: 2

    note: pretrained_buffer16_lr0.001


######### Method's Hyperparameters #########
special:
    incre_type: cil
    lambda_c_base: 5
    lambda_f_base: 1
    nb_proxy: 10

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin8: 
        cosine_resnet18:
            opt_type: sgd
            scheduler: cos
            epochs: 200 # 160
            lrate: 0.001
            batch_size: 32
            weight_decay: 0.0005
            
            epochs_finetune: 100
            lrate_finetune: 0.001

            layer_names: ['layer1', 'layer2', 'layer3', 'layer4']

            num_workers: 4
            
