######### Basic Settings #########
basic:
    device: '7'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: mas
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet32
    pretrained: false
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    # memory_size: 2000
    # fixed_memory: false
    # sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10


######### Method's Hyperparameters #########
special:
    incre_type: til
    lamda: 1
    alpha: 0.9

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet32:
            num_workers: 8
            opt_type: sgd
            init_epochs: 200 # 200
            init_lrate: 0.1
            init_scheduler: multi_step
            init_milestones: [60,120,170]
            init_lrate_decay: 0.1
            init_weight_decay: 0.0005

            epochs: 180 # 180
            lrate: 0.1
            scheduler: multi_step
            milestones: [70, 120,150]
            lrate_decay: 0.1
            batch_size: 128
            weight_decay: 0.0002
            
