######### Basic Settings #########
basic:
    device: '1'
    seed: [42, 100, 1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: finetune_il
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: mcr
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 80
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 2
    increment: 2

    note: pretrained_buffer80_lr0.001

######### Method's Hyperparameters #########
special:
    incre_type: cil
    
######### Experiment Settings for Datasets #########
options:
    skin8:        
        resnet18:
            img_size: 224
            opt_type: sgd
            weight_decay: 0.0005
            epochs: 200 # 200
            lrate: 0.001
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            batch_size: 32
            num_workers: 4
