######### Basic Settings #########
basic:
    device: '0'
    seed: [42, 100, 1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin8
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dynamic_er
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: mcr

    # Backbone Choises: resnet18
    backbone: resnet18
    pretrained: false # false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 40
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 2
    increment: 2

    logger_type: tensorboard

    note: buffer40

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin8:        
        resnet18:
            img_size: 224
            opt_type: sgd
            epochs: 170 # 170
            lrate: 0.01
            scheduler: multi_step
            milestones: [100,120]
            lrate_decay: 0.1
            weight_decay: 0.0005
            batch_size: 32
            num_workers: 4

            epochs_finetune: 50 # 200
            lrate_finetune: 0.01
            milestones_finetune: [15, 30]