######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: der
    # eval_metric Choises: acc, recall
    eval_metric: acc

    apply_nme: false

    # Backbone Choises: resnet18
    backbone: resnet18
    pretrained: false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10

    note: seed1997
    # test_epoch: 40

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet32:
            opt_type: sgd
            epochs: 170 # 170
            lrate: 0.1
            scheduler: multi_step
            milestones: [100,120]
            lrate_decay: 0.1
            weight_decay: 0.0005
            batch_size: 128
            num_workers: 4
        
        resnet18:
            img_size: 224
            opt_type: sgd
            epochs: 170 # 170
            lrate: 0.1
            scheduler: multi_step
            milestones: [100,120]
            lrate_decay: 0.1
            weight_decay: 0.0005
            batch_size: 128
            num_workers: 4